function [fitresult, gof] = createFit(tauRange, Sii)
%CREATEFIT(TAU,S22)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Tau
%      Y Output: S22
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Sep-2015 13:30:40


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Tau, S22 );

% Set up fittype and options.
ft = fittype( 'poly1' );
excludedPoints = excludedata( xData, yData, 'Domain', [x2,-1] );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'S22 vs. Tau', 'Excluded S22 vs. Tau', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel Tau
ylabel S22
grid on


